### ISSUE TITLE
Error with bundler 2.3.19

### ISSUE THREAD

**Issue by Paxa** [tarnowsc/bundler-override#5]
I use it this way

```ruby
plugin 'bundler-override'
require File.join(Bundler::Plugin.index.load_paths("bundler-override")[0], "bundler-override") rescue nil

# ...

override 'rails-dom-testing', drop: ['nokogiri']
```

and I got the error:

```
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `name' for an instance of String
  /Users/pavel/Work/gobills/autopay_journey_monitoring/.bundle/plugin/gems/bundler-override-0.1.0/lib/bundler/override/specset_patch.rb:10:in `specs_for_dependency'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/spec_set.rb:25:in `block in for'
  <internal:kernel>:187:in `loop'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/spec_set.rb:19:in `for'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:25:in `resolve'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/definition.rb:480:in `reresolve'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/definition.rb:283:in `resolve'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/definition.rb:181:in `resolve_remotely!'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/plugin/installer.rb:36:in `install_definition'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/plugin.rb:114:in `block in gemfile_install'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/settings.rb:132:in `temporary'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/plugin.rb:101:in `gemfile_install'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/cli/install.rb:57:in `run'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/cli.rb:255:in `block in install'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/settings.rb:132:in `temporary'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/cli.rb:254:in `install'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/cli.rb:31:in `dispatch'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/cli.rb:25:in `start'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/exe/bundle:48:in `block in <top (required)>'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bundler-2.3.19/exe/bundle:36:in `<top (required)>'
  /Users/pavel/.rbenv/versions/3.3.1/bin/bundle:25:in `load'
  /Users/pavel/.rbenv/versions/3.3.1/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.3.19
  Platforms   ruby, arm64-darwin-23
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [arm64-darwin-23]
  Full Path   /Users/pavel/.rbenv/versions/3.3.1/bin/ruby
  Config Dir  /Users/pavel/.rbenv/versions/3.3.1/etc
RubyGems      3.5.9
  Gem Home    /Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
  Gem Path    /Users/pavel/.gem/ruby/3.3.0:/Users/pavel/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0
  User Home   /Users/pavel
  User Path   /Users/pavel/.gem/ruby/3.3.0
  Bin Dir     /Users/pavel/.rbenv/versions/3.3.1/bin
OpenSSL       
  Compiled    OpenSSL 3.2.0 23 Nov 2023
  Loaded      OpenSSL 3.2.0 23 Nov 2023
  Cert File   /opt/homebrew/etc/openssl@3/cert.pem
  Cert Dir    /opt/homebrew/etc/openssl@3/certs
Tools         
  Git         2.39.3 (Apple Git-146)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

**Comment by tarnowsc** [comment]
Should be fixed in version 0.2.0 https://rubygems.org/gems/bundler-override/versions/0.2.0
